x-variables:
  - &wiki-image ${WIKI_IMAGE:-ghcr.io/gesinn-it-pub/openresearch-stack:dev}
  - &environment_mysql_host MYSQL_HOST=mysql
  - &environment_mysql_root_password MYSQL_ROOT_PASSWORD=database
  - &volume_wiki_images wiki-images:/var/www/html/images

services:

  wiki:
    image: *wiki-image
    volumes:
      - wiki-data:/data
      - *volume_wiki_images
      - ./tests/backstop/backstop_data:/var/www/html/backstop
      - ./tests/http-integration:/http-integration-test
      - /http-integration-test/node_modules/
    environment:
      - WIKI_DOMAIN=${WIKI_DOMAIN:-localhost}
      - WIKI_PORT=${WIKI_PORT:-80}
      - WIKI_LANGUAGE=en
      - ELASTICSEARCH_HOST=elasticsearch
      - *environment_mysql_host
    extra_hosts:
      - "host.docker.internal:host-gateway"
  
  memcached:
    image: memcached:latest

  elasticsearch:
    ## MW recommends to use their own images and sticking with the version even if a newer ES is available
    ## https://gitlab.wikimedia.org/repos/search-platform/cirrussearch-elasticsearch-image
    ## https://docker-registry.wikimedia.org/repos/search-platform/cirrussearch-elasticsearch-image/tags/
    image: docker-registry.wikimedia.org/repos/search-platform/cirrussearch-elasticsearch-image:v7.10.2-12
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

  mysql:
    image: mysql:8
    command: --innodb_buffer_pool_size=1024M --innodb_log_file_size=256M
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - *environment_mysql_root_password

  wait-for-wiki:
    image: mintel/docker-wait-for-it
    entrypoint: ['/opt/wait-for-it.sh', 'wiki:80', '-t', '120']
    profiles:
      - no-up

  backstop:
    image: backstopjs/backstopjs:6.0.4
    volumes:
      - ./backstop:/src
    profiles:
      - no-profile

volumes:
  wiki-data:
  wiki-images:
  elasticsearch-data:
  mysql-data: